ebook/en/content/004-the-head-command.md

Details about head command is added

---

ebook/en/content/014-the-mkdir-command.md

- [4] ✨ New Chapter
added mkdir Linux/Unix command examples.

mkdir command examples

---

ebook/en/content/004-the-head-command.md
ebook/en/content/005-the-tail-command.md

Added documentation for tail command

---

ebook/en/content/001-the-ls-command.md

Adding 001-the-ls-command.md contents

---

ebook/en/content/043-the-clear-command.md

added the clear command

---

README.md
ebook/en/content/005-the-tail-command.md
ebook/en/content/028-the-history-command.md
ebook/en/content/101-the-chown-command.md

Added the history command
Added the chown command
Edited the tail command
Thx for the great idea 🔥

add history command, add chown command and update tail command

---

README.md
ebook/en/content/013-the-uname-command.md

In order to help complete the book, this commit adds the details around
the `uname` linux command.

Add uname command

---

README.md
ebook/en/content/056-the-shutdown-command.md

> ## What type of PR is this? (check all applicable)
> * [ ]  ♻️ Refactor
> * [x]  ✨ New Chapter
> * [ ]  🐛 Bug Fix/Typo
> * [ ]  👷 Optimization
> * [ ]  📝 Documentation Update
> * [ ]  🚩 Other
> 
> ## Description
> In order to help complete the book, this commit adds the details around the `shutdown` linux command.
> 
> ## Related Tickets & Documents
> ## Added to documentation?
> * [x]  📜 readme
> * [ ]  🙅 no documentation needed

Add shutdown command

---

README.md
ebook/en/content/024-the-man-command.md
ebook/en/content/056-the-shutdown-command.md

> ## What type of PR is this? (check all applicable)
> * [ ]  ♻️ Refactor
> * [x]  ✨ New Chapter
> * [ ]  🐛 Bug Fix/Typo
> * [ ]  👷 Optimization
> * [ ]  📝 Documentation Update
> * [ ]  🚩 Other
> 
> ## Description
> In order to help complete the book, this commit adds details around the `man` linux command.
> 
> ## Related Tickets & Documents
> ## Added to documentation?
> * [x]  📜 readme
> * [ ]  🙅 no documentation needed

Add the man command

---

ebook/en/content/054-the-zip-command.md

Completed the 054-the-zip-command md file

Completed 054-the-zip-command

---

ebook/en/content/007-the-touch-command.md

Added touch command.

---

Guidelines.md

- [X ] 📝 Documentation Update
Added a basic guidelines file, think one is necessary due to all the different people that will be writing pages, having one to help keep pages similiar in organisation and format will be useful.
This is just a basic guidelines to start off with and I think having more people give their say on what they should be will help flesh it out and push this project forward cleanly!
- [X ] 🙅 no documentation needed

Added first iteration of guidelines

---

ebook/en/content/090-the-awk-command.md
ebook/en/content/096-the-whereis-command.md

Added description for a few commands.

awk and whereis command update

---

ebook/en/content/030-the-lscpu-command.md

added lscpu command examples

---

ebook/en/content/085-the-ping-command.md

ping command

---

ebook/en/content/059-the-sort-command.md
ebook/en/content/085-the-ping-command.md

'sort' command

---

ebook/en/content/070-the-service-command.md

Added service command

---

README.md
ebook/en/content/002-the-cd-command.md

Cd Command

---

README.md
ebook/en/content/039-the-nano-command.md

Added nano command

---

ebook/en/content/077-the-sleep-command.md

Added the sleep command

---

ebook/en/content/002-the-cd-command.md

Fix numbering in cd page

---

README.md
ebook/en/content/015-the-gzip-command.md

Added the GZIP command chapter in the book

updated the gzip command

---

ebook/en/content/047-the-yes-command.md

Added yes command

---

ebook/en/content/031-the-cp-command.md

added the cp command (descriptively and neatly)

---

ebook/en/content/055-the-unzip-command.md

Completed the 055-the-unzip-command

Completed 055-the-unzip-command

---

ebook/en/content/003-the-cat-tac-command.md
ebook/en/content/100-the-vim-command.md

I have updated the chapter [003](https://github.com/bobbyiliev/101-linux-commands-ebook/blob/main/ebook/en/content/003-the-cat-tac-command.md) and [100](https://github.com/bobbyiliev/101-linux-commands-ebook/blob/main/ebook/en/content/100-the-vim-command.md).
Added flags, history and workflow.
This commit adds #25

Updating vim and cat commands

---

ebook/en/content/032-the-mv-command.md

Add details about the mv command with relevant examples and additional flags
https://linux.die.net/man/1/mv is the man page for the mv command

add info about the mv command

---

ebook/en/content/088-the-whois-command.md

added whois command

---

ebook/en/content/011-the-help-command.md

011-add-the-help-command

---

Guidelines.md

Fixed typos in Guidelines.md

---

ebook/en/content/034-the-kill-command.md

Add Kill Command

---

ebook/en/content/012-the-factor-command.md

Updated factor command

---

ebook/en/content/025-the-passwd-command.md

025-add-the-passwd-command

---

ebook/en/content/076-the-scp-command.md

Adds the scp command

---

README.md
ebook/en/content/035-the-killall-command.md

Adds `killall` command
https://destroyallsoftware.com

Adds the killall command

---

README.md
ebook/en/content/084-the-du-command.md

Add guide  about the du command.

---

README.md
ebook/en/content/021-the-echo-command.md

Added the information about the `echo` command

added the information about the `echo` command

---

ebook/en/content/031-the-cp-command.md

Updated `cp` linux command manual

Added cp command manual

---

ebook/en/content/022-the-finger-command.md
ebook/en/content/026-the-w-command.md
ebook/en/content/088-the-whois-command.md

added finger command

---

ebook/en/content/029-the-login-command.md

please review the changes I want to contribute it as my hacktoberfest 2021
This is a new chapter on login command #86

I have added the login command

---

ebook/en/content/046-the-curl-command.md

046-add-the-curl-command

---

ebook/en/content/005-the-tail-command.md

fix grammar issues

---

ebook/en/content/002-the-cd-command.md

Remove `cd ..` - it doesn't return to previous directory, just lower.
Also, add `cd`, which will go to `~`, even without `~`.

remove cd .. - it doesn't return to previous directory, just lower

---

ebook/en/content/044-the-su-command.md

044-add-the-su-command

---

ebook/en/content/095-the-tree-command.md

Signed-off-by: Daniel Stamer <dan@hello-world.sh>
Adding description of `tree` command.

add tree command page

---

ebook/en/content/093-the-nohub-command.md

Signed-off-by: Daniel Stamer <dan@hello-world.sh>
Describe `nohup` command.

add nohup command chapter

---

README.md
ebook/en/content/068-the-lsof-command.md

Added documentation for `lsof` command.
https://github.com/bobbyiliev/101-linux-commands-ebook/blob/main/ebook/en/content/068-the-lsof-command.md

`lsof` command documentation added

---

ebook/en/content/009-the-bc-command.md

Update examples in 009-the-bc-command.md

---

README.md
ebook/en/content/041-the-ifconfig-command.md

added a description for ifconfig command

added description for ifconfig command

---

README.md

please consider this for hacktoberfest 2021
Added the find and rmdir commands in the README.md

adding find and rmdir commands

---

README.md
ebook/en/content/033-the-ps-command.md

Added a chapter for the PS command.
Closes #105

Ps chapter

---

README.md
ebook/en/content/038-the-hostname-command.md

added a description for hostname

added a description for hostname

---

README.md
ebook/en/content/036-the-env-command.md

Added the env command description to chapter 36

Add env command

---

ebook/en/content/063-the-tar-command.md

Added tar command with examples and description.

added tar command

---

README.md
ebook/en/content/079-the-stat-command.md

This PR adds the `stat` command chapter.
Corresponds to issue #110

Add the stat command

---

README.md
ebook/en/content/019-the-top-htop-command.md

Adds top/htop chapter

---

README.md
ebook/en/content/091-the-crontab-command.md

added description for crontab

---

ebook/en/content/080-the-useradd-command.md

Completed the 080-the-useradd-command file

Added 080-the-useradd-command

---

ebook/en/content/080-the-useradd-command.md
ebook/en/content/081-the-userdel-command.md

Completed the 081-the-userdel-command.md file

Added 081-the-userdel-command file

---

ebook/en/content/071-the-vmstat-command.md

added vmstat command

---

ebook/en/content/098-the-cut-command.md

Manual for `cut` linux command

Added cut command manual

---

ebook/en/content/103-the-rmdir-command.md

Added rmdir command manual

---

ebook/en/content/033-the-ps-command.md

Added additional options table for ps command.
- [] 📝 Documentation Update
Updated the ps command chapter with more info

Added additional options table for ps command

---

ebook/en/content/042-the-ip-command.md

Added ip command with description,examples and additional flags

add ip command

---

ebook/en/content/099-the-sed-command.md

Adds documentation for sed command

Add 099-sed-command manual

---

README.md
ebook/en/content/074-the-uniq-command.md

Add details regarding the uniq command, along with a few commonly used additional commands and flags.
https://man7.org/linux/man-pages/man1/uniq.1.html is the linux manual page for uniq

Added 074-uniq-command

---

README.md
ebook/en/content/104-the-lsblk-command.md

Added a new chapter for the Linux ``lsblk`` command.
I'd appreciate it if you could add a ``hacktoberfest-accepted`` tag to this Pull Request. :smile: 
[lsblk man page](https://linux.die.net/man/8/lsblk)

Added the Linux lsblk command.

---

ebook/en/content/048-the-last-command.md

added last command

---

ebook/en/content/102-the-find-command.md

Add 102-the-find-command.md 

---

ebook/en/content/060-the-paste-command.md

Paste command

---

ebook/en/content/064-the-gunzip-command.md

Gunzip command

---

ebook/en/content/056-the-shutdown-command.md

Typo fixed
Fixed typo by changing "you" to "your" and corrected the spelling of "scheduled".

Fixed typo in 056-the-shutdown-command.md

---

ebook/en/content/123-the-xeyes-command.md

Add the xeyes command

---

ebook/en/content/041-the-ifconfig-command.md

Added more examples to the `ifconfig` command

Added more examples to 041-the-ifconfig-command.md

---

ebook/en/content/051-the-sudo-command.md

add example in sudo command

---

ebook/en/content/078-the-split-command.md

Modified split command

---

ebook/en/content/089-the-ssh-command.md

```diff
- protocal
+ protocol 
```

Corrected the protocol spelling

---

ebook/en/content/107-the-grep-command.md

-F flag is useful to find all the lines of a file that contain a particular word
Source: https://linuxcommand.org/lc3_man_pages/grep1.html

grep -F added

---

ebook/en/content/001-the-ls-command.md

Update the ls command and added few helpful flags

---

ebook/en/content/076-the-scp-command.md

Added an example to copy file though a jump ssh host server

---

README.md
ebook/en/content/130-the-pidof-command.md

Added the pidof command along with examples

Added the pidof command

---

ebook/en/content/134-the-cmp-command.md

added cmp command

---

ebook/en/content/001-the-ls-command.md
ebook/en/content/068-the-lsof-command.md
ebook/en/content/085-the-ping-command.md

When documenting the `ls` command, consider providing detailed steps for readers who want to customize their shell environment using the `.bashrc` file. Explaining how to enhance the `ls` command's behavior through modifications to the `.bashrc` file can be highly beneficial.
Fixed a typo present in the description of lsof
In the context of the `ping` command, it's valuable to clarify the importance of latency and why it matters in networking. Explaining how latency affects network performance and the significance of ping results can help readers better interpret and utilize the command's output.
Providing clear and concise explanations of command options is essential, especially for options like `-c` (count) and `-s` (size) in the `ping` command. Clarifying the distinctions between these …

improve-existing-chapters/ls-lsof-ping-files-committed

---

ebook/en/content/024-the-man-command.md

Added an example to markdown file of man comman of linux

Added a new example to man command markdown file

---

.github/workflows/ibis.yml

update read online link in releases GH workflow
**ref: #396**
Closes #396

Update read online link in release workflow

---

ebook/en/content/136-the-wall-command.md

Hi again!
This pull request is another contribution towards Issue #190, focusing on a complete rewrite of the `wall` command chapter to improve its clarity and practical utility.
Here is a summary of the key enhancements:
* **Improved Structure:** The chapter has been reordered for a more logical flow, making it easier for a new user to follow.
* **Added Command Outputs:** All examples now include the expected output that would appear on a user's terminal, providing crucial context.
* **New Example Added:** A new, practical example has been included to demonstrate how to send a multi-line message using standard input (`Ctrl+D`), which is a common use case.
* **Clearer Options Table:** The options are now presented in a clean, readable Markdown table.
These changes aim to make the chapter …

docs: Rewrite and enhance 'wall' command chapter

---

Guidelines.md

ReadME edit to make it read better

Update Guidelines.md to ensure it reads better

---

ebook/en/content/100-the-vim-command.md

This PR includes the following updates related to Vim commands:
- Fixed a typo (`o` : move to begining of line . Here it should be 0 instead of o).  
- Added new useful Vim commands to enhance the reference or guide (:x , :linenumber , dw , di" ,diw , dip ) .

docs : add new commands in vim command section and update a command for vim
